version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: learn_fun_nest_dev_db
    networks:
      - phucdo2601
networks:
  phucdo2601: